### ISSUE TITLE
Remediation automatique NOK

### ISSUE THREAD

**Issue by stephanebarcet** [sfraysse/moodle-assessmentpath#1]
Sur un assessment path, je crée une première étape avec un test initial et un test remedial.
Le test initial a pour paramètres :
- Dispo : Ouvert
- Tentatives : illimitées
- Notation : dernière
- Interdire tentative après réussite : NON
- Correction : immédiate
Le test de remédiation a les mêmes paramètres, sauf pour la disponibilité : Automatique.

Je joue le test, en echec. La remédiation ne s'ouvre pas (NOK).
Je peux rejouter le test. Si je suis en réussite, la remédiation ne s'ouvre pas (OK).
Je rejoue le test en echec. Toujours pas de remédiation accessible.

**Comment by sfraysse** [comment]
Pour moi c'est pas un bug mais un comportement souhaité.
Le remédial ne s'ouvre que si l'on a raté le test initial et que l'on n'a plus d'essai.
Comme le test initial est en essais illimités, il ne peut pas y avoir d'ouverture du remédial.

**Comment by stephanebarcet** [comment]
OK
